Project/BakeryStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Project/core/urls.py
from django.urls import  path
from django.conf import settings
from django.conf.urls.static import static

from . import views
from .views import HomeView, ItemDetailView, add_to_cart, remove_from_cart, OrderSummaryView, \
    remove_item_from_cart, add_item_to_cart, CheckoutView, CategoryView, AboutView

app_name = 'core'

urlpatterns = [
    path('shop/', HomeView.as_view(), name='shop'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', views.contact_us, name='contact'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>', remove_from_cart, name='remove-from-cart'),
    path('remove_item_from_cart/<slug>', remove_item_from_cart, name='remove_item_from_cart'),
    path('add_item_to_cart/<slug>', add_item_to_cart, name='add_item_to_cart'),
    path('search/', CategoryView.as_view(), name='search'),
    path('', views.landing_page, name='landing'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Project/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="about" style="background-color: whitesmoke">
    <div class="container">
        <h3>About</h3>
        <img src="{% static '/img/about.jpg' %}" class="img-responsive" title="image-name"/><br/>
        <p></p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
            ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
            nulla pariatur. Lorem ipsum dolor sit amet consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
            labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
            dolore eu fugiat nulla pariatur.</p>
        <p> Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est
            laborumLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
            et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
            ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
            fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
            mollit anim id est laborumExcepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
            mollit anim id est laborum</p>
        <p>tncididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
            laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
            esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa
            qui officia deserunt mollit anim id est laborum</p>
    </div>
</div>
{% endblock %}

Project/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{#<Head#}
{% include "head.html" %}
{#</HEAD>#}
{% include "navbar.html" %}
<body>
<div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show red lighten-5" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
</div>
{% block content %}
{% endblock content %}

{% block extra_body %}
{% endblock %}

{% include 'footer.html' %}
{% include "scripts.html" %}
</body>
</html>

Project/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="content" style="background-color: whitesmoke;">
        <div class="container">
            <h2>Kontakt</h2>
            <!----start-main-content----->
            <div class="main-content">
                <!---start-contact---->
                <div class="contact">
                    <div class="contact_info">
                        <h3>Znajdziesz nas tutaj</h3>
                        <div class="map">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d512548.72980999434!2d-66.3067789165926!3d18.684467114478952!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c0366eb878aa03d%3A0x250dcd3a342491ec!2sCarolina%2C%20Puerto%20Rico!5e0!3m2!1sen!2sus!4v1607012813989!5m2!1sen!2sus"
                                    width="100%" height="275" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                            <br><small><a
                                style="color:#666;text-align:left;font-size:12px">View Larger Map</a></small>
                        </div>
                    </div>
                    <div class="section group">
                        <div class="col span_1_of_3">

                            <div class="company_address">
                                <h3>Informacje o piekarni:</h3>
                                <p>Księcia Janusza</p>
                                <p>01-241 Wola, Warszawa</p>
                                <p>Polska</p>
                                <p>Phone:(86)661 845 255</p>
                                <p>Fax: (862) 661 835 215</p>
                                <p>Email: <span>contact@bakingcorner.com</span></p>
                                <p>Jesteśmy na: <span><a href="http://www.facebook.com" target="_blank">Facebook</a></span>, <span><a href="http://www.twitter.com" target="_blank">Twitter</a></span></p>
                            </div>
                        </div>
                        <div class="col span_2_of_3">
                            <div class="contact-form">
                                <h3>Kontakt</h3>
                                <form method="POST">
                                    {% csrf_token %}
                                    <div>
                                        <span><label>NAME</label></span>
                                        {{  form.name }}
                                    </div>
                                    <div>
                                        <span><label>E-MAIL</label></span>
                                        {{  form.email }}
                                    </div>
                                    <div>
                                        <span><label>MOBILE</label></span>
                                        {{  form.phone }}
                                    </div>
                                    <div>
                                        <span><label>SUBJECT</label></span>
                                        {{  form.message }}
                                    </div>
                                    <div>
                                        <span><input type="submit" value="Submit"></span>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                    <!---End-contact---->
                </div>
                <div class="clear"></div>
                <!----End-main-content----->
            </div>
        </div>
    </div>
{% endblock %}

Project/templates/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}{% endblock %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,vietnamese"
    rel="stylesheet">
</head>

Project/templates/home.html
{% extends 'base.html' %}
{% load static %}F
{% block content %}
    <!--Main layout-->
    <main>
        <div class="container" style="margin-top: 60px;">

            <!--Navbar-->
            {#        Lub red darken-4#}
            <nav class="navbar navbar-expand-lg navbar-dark mdb-color red lighten-2 mt-3 mb-5">

                <!-- Navbar brand -->
                <span class="navbar-brand">Categories:</span>

                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">

                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">
                        {% if category_menu %}
                            <li class="nav-item active">
                                <a class="nav-link" href="/shop">Wszystkie</a>
                                {#              <a class="nav-link" href="{% url 'core:categories' %}">{{ item }}</a>#}
                            </li>
                            {% for item in category_menu %}
                                <li class="nav-item active">
                                    <a class="nav-link" href="?category={{ item.id }}">{{ item.name }}</a>
                                    {#              <a class="nav-link" href="{% url 'core:categories' %}">{{ item }}</a>#}
                                </li>
                            {% endfor %}
                        {% endif %}
                    </ul>

                    <form class="form-inline" method="GET" action="{% url 'core:search' %}">
                        <div class="md-form my-0">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search" name="search"
                                   aria-label="Search">
                        </div>
                    </form>
                </div>
                <!-- Collapsible content -->

            </nav>
            <!--/.Navbar-->
            <!--Section: Products v.3-->
            <section class="text-center mb-4" style="margin-top: 40px">

                <div class="row wow fadeIn">
                    {% if all_search_results %}
                        {% for item in all_search_results %}
                            <div class="col-lg-3 col-md-6 mb-4">
                                <!--Card-->
                                <div class="card">
                                    <!--Card image-->
                                    <div class="view overlay" style="float: left;">
                                        <img src="{{ item.image.url }}" class="card-img-top"
                                             style="width: 260px; height: 160px;"
                                             alt="">
                                        <a href="{{ item.get_absolute_url }}">
                                            <div class="mask rgba-white-slight"></div>
                                        </a>
                                    </div>
                                    <!--Card image-->
                                    <!--Card content-->
                                    <div class="card-body text-center">
                                        <!--Category & Title-->
                                        <a href="" class="grey-text">
                                            <h5>{{ item.category }}</h5>
                                        </a>
                                        <h5>
                                            <strong>
                                                <a href="{{ item.get_absolute_url }}"
                                                   class="dark-grey-text"> {{ item.title }}</a>
                                                <div>
                                                    {% if item.label == 'P' %}
                                                        <span class="badge badge-pill primary-color">Nowość</span>
                                                    {% elif item.label == 'S' %}
                                                        <span class="badge badge-pill secondary-color">Wyprzedaż</span>
                                                    {% elif item.label == 'D' %}
                                                        <span class="badge badge-pill danger-color">Promocja</span>
                                                    {% elif item.label == '' %}
                                                        <span class="badge badge-pill danger-color"></span>
                                                    {% endif %}
                                                </div>
                                            </strong>
                                        </h5>
                                        <h4 class="font-weight-bold blue-text">
                                            <strong>
                                                {% if item.disc_price|floatformat:2 %}
                                                    {{ item.disc_price|floatformat:2 }}
                                                {% else %}
                                                    {{ item.price|floatformat:2 }}
                                                {% endif %} zł
                                            </strong>
                                        </h4>
                                    </div>
                                    <!--Card content-->
                                </div>
                                <!--Card-->
                            </div>
                        {% empty %}
                            None to display
                        {% endfor %}
                    {% else %}
                        {% for item in cakes %}
                            <div class="col-lg-3 col-md-6 mb-4">
                                <!--Card-->
                                <div class="card">
                                    <!--Card image-->
                                    <div class="view overlay" style="float: left;">
                                        <img src="{{ item.image.url }}" class="card-img-top"
                                             style="width: 260px; height: 160px;"
                                             alt="">
                                        <a href="{{ item.get_absolute_url }}">
                                            <div class="mask rgba-white-slight"></div>
                                        </a>
                                    </div>
                                    <!--Card image-->

                                    <!--Card content-->
                                    <div class="card-body text-center">
                                        <!--Category & Title-->
                                        <a href="" class="grey-text">
                                            <h5>{{ item.category }}</h5>
                                        </a>
                                        <h5>
                                            <strong>
                                                <a href="{{ item.get_absolute_url }}"
                                                   class="dark-grey-text">{{ item.title }}
                                                </a>
                                                <div>
                                                    {% if item.label == 'P' %}
                                                        <span class="badge badge-pill primary-color">Nowość</span>
                                                    {% elif item.label == 'S' %}
                                                        <span class="badge badge-pill secondary-color">Wyprzedaż</span>
                                                    {% elif item.label == 'D' %}
                                                        <span class="badge badge-pill danger-color">Promocja</span>
                                                    {% endif %}
                                                </div>
                                            </strong>
                                        </h5>

                                        <h4 class="font-weight-bold blue-text">
                                            <strong>
                                                {% if item.disc_price|floatformat:2 %}
                                                    {{ item.disc_price|floatformat:2 }}
                                                {% else %}
                                                    {{ item.price|floatformat:2 }}
                                                {% endif %} zł
                                            </strong>
                                        </h4>

                                    </div>
                                    <!--Card content-->

                                </div>
                                <!--Card-->

                            </div>
                        {% endfor %}
                    {% endif %}
                </div>

            </section>

            <!--Section: Products v.3-->

            <!--Pagination-->
            {% if is_paginated %}
                <nav class="d-flex justify-content-center wow fadeIn">
                    <ul class="pagination">

                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link red lighten-3" href="?page={{ page_obj.previous_page_number }}
                                {% for key,value in request.GET.items %}
                                    {% ifnotequal key 'page' %}&{{ key }}={{ value }}
                                    {% endifnotequal %}
                                {% endfor %}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                        {% endif %}

                        <li class="page-item active">
                            <a class="page-link red lighten-2" href="?page={{ page_obj.number }}
                                {% for key,value in request.GET.items %}
                                    {% ifnotequal key 'page' %}&{{ key }}={{ value }}
                                    {% endifnotequal %}
                                {% endfor %}">
                                {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
                            </a>
                        </li>

                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link red lighten-3" href="?page={{ page_obj.next_page_number }}
                                {% for key,value in request.GET.items %}
                                    {% ifnotequal key 'page' %}&{{ key }}={{ value }}
                                    {% endifnotequal %}
                                {% endfor %}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
            <!--Pagination-->
        </div>
    </main>
    <!--Main layout-->
{% endblock %}

Project/templates/navbar.html
{% load cart_template_tags %}
{% load static %}
<!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-md red lighten-2 scrolling-navbar">
    <div class="container">

      <!-- Brand -->
{#      <a class="navbar-brand waves-effect" href="/">#}
{#        <strong class="white-text">Baking Corner</strong>#}
{#      </a>#}
        <a class="nav-link waves-effect white-text" href="/">Home
              <span class="sr-only">(current)</span>
        </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect white-text" href="/about">O nas
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link waves-effect white-text" href="/contact">Kontakt
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
          {% if request.user|cart_item_count != 0 %}
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
{#              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>#}
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block white-text"> Koszyk </span>
            </a>
          {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block white-text"> Wyloguj </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block white-text"> Zaloguj </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block white-text"> Zarejestruj </span>
            </a>
          </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

Project/templates/order-summary.html
{% extends "base.html" %}
{% block content %}
    <main>
        <div class="container">

            <div class="table-responsive text-wrap">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nazwa ciasta</th>
                        <th scope="col">Cena</th>
                        <th scope="col">Ilość</th>
                        <th scope="col">W sumie</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order_item in object.items.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_item.item.title }}</td>
                            <td>{{ order_item.item.price|floatformat:2 }} zł</td>
                            <td>
                                <a href="{% url 'core:remove_item_from_cart' order_item.item.slug %}"><i
                                        class="fas fa-minus mr-2"></i></a>
                                {{ order_item.quantity }}
                                <a href="{% url 'core:add_item_to_cart' order_item.item.slug %}"><i
                                        class="fas fa-plus ml-2"></i></a>
                            </td>
                            <td>{% if order_item.item.disc_price|floatformat:2 %}
                                {{ order_item.get_total_disc_price|floatformat:2 }} zł
                                <span class="badge badge-primary">Rabat {{ order_item.get_amount_save|floatformat:2 }} zł</span>
                            {% else %}
                                {{ order_item.get_total_price|floatformat:2 }} zł
                            {% endif %}
                                <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                    <i class="fas fa-trash float-right"></i>
                                </a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5">Your cart is empty</td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class="btn btn-primary float-right ml-02" href="/shop">Powrót do sklepu</a>
                            </td>
                        </tr>
                    {% endfor %}
                    {% if object.get_total %}
                        <tr>
                            <td colspan="4"><b>Do zapłaty</b></td>
                            <td><b>{{ object.get_total|floatformat:2 }} zł</b></td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class="btn btn-primary float-right ml-02" href="/shop">Powrót do sklepu</a>
                                <a class="btn btn-light-blue float-right" href="/checkout">Przejdź do zapłaty</a>
                            </td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </main>
{% endblock %}

Project/templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();
</script>
<script>
    $(function () {
        $('.carousel-example-1z').carousel();
    });
</script>
<script>
    addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    }
</script>

Project/templates/search.html
{% extends 'home.html' %}

{% block search %}
                <!--Navbar-->
            <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

                <!-- Navbar brand -->
                <span class="navbar-brand">Categories:</span>

                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">

                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">
                        {% if category_menu %}
                            <li class="nav-item active">
                                <a class="nav-link" href="/">Wszystkie</a>
                                {#              <a class="nav-link" href="{% url 'core:categories' %}">{{ item }}</a>#}
                            </li>
                            {% for item in category_menu %}
                                <li class="nav-item active">
                                    <a class="nav-link" href="/?category={{ item.id }}">{{ item.name }}</a>
                                    {#              <a class="nav-link" href="{% url 'core:categories' %}">{{ item }}</a>#}
                                </li>
                            {% endfor %}
                        {% endif %}
                    </ul>

                    <form class="form-inline" method="GET" action="{% url 'core:search' %}">
                        <div class="md-form my-0">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search" name="search" aria-label="Search">
                        </div>
                    </form>
                </div>
                <!-- Collapsible content -->

            </nav>
</div>
{% endblock %}